#!/usr/bin/env python3
"""Build the shipped blueprint variants.

Two controllers times four languages is eight files, and editing eight files by
hand is how a fix ends up applied to six of them. They are generated instead,
from one source blueprint plus one string file per language:

    blueprints/_source/sonos_smart_group.yaml   the English Sonos blueprint
    blueprints/_source/strings.<lang>.yaml      every visible string, translated

    ->  blueprints/sonos/en.yaml
        blueprints/sonos/nl.yaml
        blueprints/music_assistant/en.yaml
        ...

The source is parsed as YAML rather than treated as text, so a translation is
keyed by *where a string lives* - section, input, select option - instead of by
the English wording. Long descriptions can then be rewritten freely, and a
rename in the source shows up as a warning instead of a silently English field.

The Music Assistant controller drops the equalizer and home theater inputs, which
would offer nothing: Music Assistant exposes no such entities for Sonos players.

    python3 tools/build_blueprints.py             # write the variants
    python3 tools/build_blueprints.py --check     # fail if anything is stale
    python3 tools/build_blueprints.py --template nl > _source/strings.nl.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
BASE = ROOT / "custom_components" / "sonos_smart_groups" / "blueprints"
SOURCE = BASE / "_source" / "sonos_smart_group.yaml"

LANGUAGES = ["en", "nl", "de", "fr"]
CONTROLLERS = ["sonos", "music_assistant"]

# Inputs that only make sense with the Sonos integration installed.
SONOS_ONLY_INPUTS = ["copy_equalizer", "copy_home_theater"]

HEADER = (
    "# Generated by tools/build_blueprints.py - do not edit.\n"
    "# Change blueprints/_source/ and run the script instead.\n"
)


class Input:
    """A `!input name` reference."""

    def __init__(self, name: str) -> None:
        self.name = name


class Loader(yaml.SafeLoader):
    pass


class Dumper(yaml.SafeDumper):
    pass


Loader.add_constructor("!input", lambda l, n: Input(l.construct_scalar(n)))
# PyYAML always quotes a tagged scalar, so the output reads `!input 'leader'`
# rather than `!input leader`. Home Assistant's constructor strips the quotes,
# so the two are equivalent; it is only slightly less pretty.
Dumper.add_representer(
    Input, lambda d, v: d.represent_scalar("!input", v.name, style="")
)


def _represent_str(dumper, data):
    """Write anything multi-line as a literal block, so it round-trips exactly."""
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


Dumper.add_representer(str, _represent_str)


def _load(path: Path) -> dict:
    return yaml.load(path.read_text(encoding="utf-8"), Loader=Loader)


def _dump(data: dict) -> str:
    return yaml.dump(data, Dumper=Dumper, sort_keys=False, allow_unicode=True, width=88)


def _sections(meta: dict) -> dict:
    """The input sections, given the contents of the `blueprint:` key."""
    return meta["input"]


def _options(field: dict) -> list | None:
    selector = (field or {}).get("selector") or {}
    select = selector.get("select")
    if isinstance(select, dict) and isinstance(select.get("options"), list):
        if all(isinstance(o, dict) for o in select["options"]):
            return select["options"]
    return None


def _object_fields(field: dict) -> dict | None:
    selector = (field or {}).get("selector") or {}
    obj = selector.get("object")
    if isinstance(obj, dict) and isinstance(obj.get("fields"), dict):
        return obj["fields"]
    return None


def make_template(blueprint: dict) -> dict:
    """A strings file with the English text in place, ready to translate."""
    meta = blueprint["blueprint"]
    out: dict[str, Any] = {
        "blueprint": {k: meta[k] for k in ("name", "description") if k in meta},
        "sections": {},
    }

    for section_key, section in _sections(meta).items():
        entry: dict[str, Any] = {
            k: section[k] for k in ("name", "description") if k in section
        }
        fields: dict[str, Any] = {}

        for field_key, field in (section.get("input") or {}).items():
            if not isinstance(field, dict):
                continue
            item: dict[str, Any] = {
                k: field[k] for k in ("name", "description") if k in field
            }
            if options := _options(field):
                item["options"] = {
                    o["value"]: o["label"] for o in options if "label" in o
                }
            if sub := _object_fields(field):
                item["fields"] = {
                    k: v["label"]
                    for k, v in sub.items()
                    if isinstance(v, dict) and "label" in v
                }
            if item:
                fields[field_key] = item

        if fields:
            entry["inputs"] = fields
        out["sections"][section_key] = entry

    return out


def translate(blueprint: dict, strings: dict, language: str) -> None:
    """Apply a strings file to a loaded blueprint, in place."""
    meta = blueprint["blueprint"]
    missing: list[str] = []

    for key in ("name", "description"):
        if value := (strings.get("blueprint") or {}).get(key):
            meta[key] = value

    for section_key, section in _sections(meta).items():
        translated = (strings.get("sections") or {}).get(section_key)
        if translated is None:
            missing.append(section_key)
            continue

        for key in ("name", "description"):
            if value := translated.get(key):
                section[key] = value

        for field_key, field in (section.get("input") or {}).items():
            if not isinstance(field, dict):
                continue
            item = (translated.get("inputs") or {}).get(field_key)
            if item is None:
                missing.append(f"{section_key}.{field_key}")
                continue

            for key in ("name", "description"):
                if value := item.get(key):
                    field[key] = value

            if (options := _options(field)) and (labels := item.get("options")):
                for option in options:
                    if label := labels.get(option.get("value")):
                        option["label"] = label

            if (sub := _object_fields(field)) and (labels := item.get("fields")):
                for name, spec in sub.items():
                    if isinstance(spec, dict) and (label := labels.get(name)):
                        spec["label"] = label

    for name in missing:
        print(f"  warning [{language}]: no translation for {name}", file=sys.stderr)


def strip_sonos_only(blueprint: dict) -> None:
    """Remove the inputs that need the Sonos integration, in place."""
    for section in _sections(blueprint["blueprint"]).values():
        for key in SONOS_ONLY_INPUTS:
            (section.get("input") or {}).pop(key, None)

    variables = blueprint.get("variables") or {}
    for key in SONOS_ONLY_INPUTS:
        variables.pop(key, None)


def build() -> dict:
    out: dict[Path, str] = {}

    for controller in CONTROLLERS:
        for language in LANGUAGES:
            blueprint = _load(SOURCE)

            if controller != "sonos":
                strip_sonos_only(blueprint)

            if language != "en":
                path = SOURCE.parent / f"strings.{language}.yaml"
                if not path.is_file():
                    print(f"  skipping {controller}/{language}: no {path.name}")
                    continue
                strings = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
                translate(blueprint, strings, language)

            out[BASE / controller / f"{language}.yaml"] = HEADER + _dump(blueprint)

    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="do not write")
    parser.add_argument("--template", metavar="LANG", help="print a strings skeleton")
    args = parser.parse_args()

    if not SOURCE.is_file():
        print(f"Source blueprint not found: {SOURCE}", file=sys.stderr)
        return 1

    if args.template:
        print(
            f"# Strings for {args.template}. Translate the values, leave the keys.\n"
            "# Never translate: input keys, !input names, trigger ids, or the\n"
            "# `value:` of a select option - those are structural.\n"
        )
        print(_dump(make_template(_load(SOURCE))))
        return 0

    variants = build()
    stale = [
        path
        for path, content in variants.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]

    for path, content in variants.items():
        try:
            data = yaml.load(content, Loader=Loader)
            assert "blueprint" in data and "triggers" in data
        except (yaml.YAMLError, AssertionError) as err:
            print(f"  INVALID {path.relative_to(ROOT)}: {err}", file=sys.stderr)
            return 1

    if args.check:
        if stale:
            print("Out of date:", file=sys.stderr)
            for path in stale:
                print(f"  {path.relative_to(ROOT)}", file=sys.stderr)
            print("\nRun: python3 tools/build_blueprints.py", file=sys.stderr)
            return 1
        print(f"{len(variants)} variants up to date")
        return 0

    for path, content in variants.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        mark = "written" if path in stale else "unchanged"
        print(f"  {mark:9s} {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
