#!/usr/bin/env python3
"""Build the shipped blueprint variants.

Two flavours times four languages is eight files. Editing eight files by hand
is how a bugfix ends up applied to six of them, so they are generated instead:

    blueprints/_source/sonos_smart_group.yaml   the English Sonos blueprint
    blueprints/_source/strings.<lang>.yaml      translated text per input key

    ->  blueprints/sonos/en.yaml            (a copy of the source)
        blueprints/sonos/nl.yaml            (source + Dutch strings)
        blueprints/music_assistant/en.yaml  (source minus the Sonos-only bits)
        ...

The Music Assistant flavour drops everything between the markers

    # <sonos-only>
    ...
    # </sonos-only>

which is how the equalizer and home theater sections are left out: Music
Assistant exposes no such entities for Sonos players, so offering them would
be offering nothing.

Run from the repository root:

    python3 tools/build_blueprints.py
    python3 tools/build_blueprints.py --check     # fail if anything is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
BASE = ROOT / "custom_components" / "sonos_smart_groups" / "blueprints"
SOURCE = BASE / "_source" / "sonos_smart_group.yaml"

LANGUAGES = ["en", "nl", "de", "fr"]
FLAVOURS = ["sonos", "music_assistant"]

SONOS_ONLY = re.compile(
    r"^[ \t]*#[ ]*<sonos-only>.*?^[ \t]*#[ ]*</sonos-only>[ \t]*\n",
    re.DOTALL | re.MULTILINE,
)

HEADER = (
    "# Generated by tools/build_blueprints.py — do not edit.\n"
    "# Change blueprints/_source/ and run the script instead.\n"
)


def _strip_sonos_only(text: str) -> str:
    """Remove the blocks that only make sense with the Sonos integration."""
    stripped = SONOS_ONLY.sub("", text)
    if stripped == text:
        print("  warning: no <sonos-only> markers found", file=sys.stderr)
    return stripped


def _translate(text: str, strings: dict) -> str:
    """Replace English display text with its translation.

    Deliberately a plain string replacement on quoted and block values rather
    than a YAML round-trip: that keeps the comments, which are half of why the
    source is readable.
    """
    for english, translated in sorted(
        strings.items(), key=lambda kv: len(kv[0]), reverse=True
    ):
        if not translated or english == translated:
            continue
        if english not in text:
            print(f"  warning: not found in source: {english[:60]!r}", file=sys.stderr)
            continue
        text = text.replace(english, translated)
    return text


def build() -> dict[Path, str]:
    """Produce the contents of every variant."""
    source = SOURCE.read_text(encoding="utf-8")
    out: dict[Path, str] = {}

    for flavour in FLAVOURS:
        body = source if flavour == "sonos" else _strip_sonos_only(source)

        for language in LANGUAGES:
            text = body
            if language != "en":
                path = SOURCE.parent / f"strings.{language}.yaml"
                if not path.is_file():
                    print(f"  skipping {flavour}/{language}: no {path.name}")
                    continue
                strings = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
                text = _translate(text, strings)

            out[BASE / flavour / f"{language}.yaml"] = HEADER + text

    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if a file is missing or stale",
    )
    args = parser.parse_args()

    if not SOURCE.is_file():
        print(f"Source blueprint not found: {SOURCE}", file=sys.stderr)
        return 1

    variants = build()
    stale: list[Path] = []

    for path, content in variants.items():
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    # Every generated file must still be a valid blueprint.
    class Loader(yaml.SafeLoader):
        pass

    Loader.add_multi_constructor(
        "!",
        lambda loader, suffix, node: loader.construct_scalar(node)
        if isinstance(node, yaml.ScalarNode)
        else (
            loader.construct_sequence(node)
            if isinstance(node, yaml.SequenceNode)
            else loader.construct_mapping(node)
        ),
    )
    for path, content in variants.items():
        try:
            data = yaml.load(content, Loader=Loader)
            assert "blueprint" in data, "no blueprint key"
            assert "triggers" in data, "no triggers"
        except (yaml.YAMLError, AssertionError) as err:
            print(f"  INVALID {path.relative_to(ROOT)}: {err}", file=sys.stderr)
            return 1

    if args.check:
        if stale:
            print("Out of date:", file=sys.stderr)
            for path in stale:
                print(f"  {path.relative_to(ROOT)}", file=sys.stderr)
            print("\nRun: python3 tools/build_blueprints.py", file=sys.stderr)
            return 1
        print(f"{len(variants)} variants up to date")
        return 0

    for path in sorted(variants):
        mark = "written" if path in stale else "unchanged"
        print(f"  {mark:9s} {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
